# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-shapefile"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marc Dietrichstein"]
  s.date = "2012-02-21"
  s.description = "Pure ruby parser for .shp shapefiles and .dbf attribute files.\nSupported shapes: NullShape, Point, MultiPoint, PolyLine and Polygon."
  s.email = "marc@dietrichstein.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/read_all.rb",
    "lib/converters.rb",
    "lib/shapefile.rb",
    "spec/shp_header_spec.rb",
    "spec/spec_helper.rb",
    "test-data/110m-admin-0-countries/110m_admin_0_countries.dbf",
    "test-data/110m-admin-0-countries/110m_admin_0_countries.prj",
    "test-data/110m-admin-0-countries/110m_admin_0_countries.shp",
    "test-data/110m-admin-0-countries/110m_admin_0_countries.shx"
  ]
  s.homepage = "http://github.com/toastbrot/ruby-shapefile"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "shapefile (.shp) parser written in pure ruby"
  s.test_files = [
    "examples/read_all.rb",
    "spec/shp_header_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dbf>, [">= 1.5.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<dbf>, ["> 1.5.0"])
    else
      s.add_dependency(%q<dbf>, [">= 1.5.0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<dbf>, ["> 1.5.0"])
    end
  else
    s.add_dependency(%q<dbf>, [">= 1.5.0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<dbf>, ["> 1.5.0"])
  end
end

